/* SPDX-License-Identifier: LGPL-2.1-or-later */
/* Generated by tools/generate_d3d9_inventory.py; do not edit. */
#ifndef PW_D3D9_INVENTORY_H
#define PW_D3D9_INVENTORY_H
#define PW_D3D9_HEADER_SHA256 "fb49b3c44acec5e100a5c0ff1622f7d0207842d87fc513b49047a818e8c351b2"
/* Policies are obligations, not an automatic runtime enable list. */
enum pw_d3d9_method_policy {
    PW_D3D9_POLICY_UNSUPPORTED, PW_D3D9_POLICY_LOCAL_IDENTITY,
    PW_D3D9_POLICY_SYNC_FACTORY
};
/* X(interface, slot, name, return_type, (explicit parameters), policy).
 * Explicit parameters include the typed self pointer. Native signatures
 * are for compile checks/local proxies; never copy them onto the wire. */
#define PW_D3D9_METHODS_IDirect3D9(X) \
    X(IDirect3D9, 0, QueryInterface, HRESULT, (IDirect3D9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3D9, 1, AddRef, ULONG, (IDirect3D9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3D9, 2, Release, ULONG, (IDirect3D9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3D9, 3, RegisterSoftwareDevice, HRESULT, (IDirect3D9 *self, void* pInitializeFunction), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3D9, 4, GetAdapterCount, UINT, (IDirect3D9 *self), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 5, GetAdapterIdentifier, HRESULT, (IDirect3D9 *self, UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER9* pIdentifier), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 6, GetAdapterModeCount, UINT, (IDirect3D9 *self, UINT Adapter, D3DFORMAT Format), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 7, EnumAdapterModes, HRESULT, (IDirect3D9 *self, UINT Adapter, D3DFORMAT Format, UINT Mode, D3DDISPLAYMODE* pMode), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 8, GetAdapterDisplayMode, HRESULT, (IDirect3D9 *self, UINT Adapter, D3DDISPLAYMODE* pMode), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 9, CheckDeviceType, HRESULT, (IDirect3D9 *self, UINT iAdapter, D3DDEVTYPE DevType, D3DFORMAT DisplayFormat, D3DFORMAT BackBufferFormat, BOOL bWindowed), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 10, CheckDeviceFormat, HRESULT, (IDirect3D9 *self, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, DWORD Usage, D3DRESOURCETYPE RType, D3DFORMAT CheckFormat), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 11, CheckDeviceMultiSampleType, HRESULT, (IDirect3D9 *self, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SurfaceFormat, BOOL Windowed, D3DMULTISAMPLE_TYPE MultiSampleType, DWORD* pQualityLevels), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 12, CheckDepthStencilMatch, HRESULT, (IDirect3D9 *self, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 13, CheckDeviceFormatConversion, HRESULT, (IDirect3D9 *self, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SourceFormat, D3DFORMAT TargetFormat), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 14, GetDeviceCaps, HRESULT, (IDirect3D9 *self, UINT Adapter, D3DDEVTYPE DeviceType, D3DCAPS9* pCaps), PW_D3D9_POLICY_SYNC_FACTORY) \
    X(IDirect3D9, 15, GetAdapterMonitor, HMONITOR, (IDirect3D9 *self, UINT Adapter), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3D9, 16, CreateDevice, HRESULT, (IDirect3D9 *self, UINT Adapter, D3DDEVTYPE DeviceType, HWND hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS* pPresentationParameters, struct IDirect3DDevice9** ppReturnedDeviceInterface), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DVolume9(X) \
    X(IDirect3DVolume9, 0, QueryInterface, HRESULT, (IDirect3DVolume9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVolume9, 1, AddRef, ULONG, (IDirect3DVolume9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVolume9, 2, Release, ULONG, (IDirect3DVolume9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVolume9, 3, GetDevice, HRESULT, (IDirect3DVolume9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolume9, 4, SetPrivateData, HRESULT, (IDirect3DVolume9 *self, REFGUID guid, const void *data, DWORD data_size, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolume9, 5, GetPrivateData, HRESULT, (IDirect3DVolume9 *self, REFGUID refguid, void* pData, DWORD* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolume9, 6, FreePrivateData, HRESULT, (IDirect3DVolume9 *self, REFGUID refguid), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolume9, 7, GetContainer, HRESULT, (IDirect3DVolume9 *self, REFIID riid, void** ppContainer), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolume9, 8, GetDesc, HRESULT, (IDirect3DVolume9 *self, D3DVOLUME_DESC* pDesc), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolume9, 9, LockBox, HRESULT, (IDirect3DVolume9 *self, D3DLOCKED_BOX *locked_box, const D3DBOX *box, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolume9, 10, UnlockBox, HRESULT, (IDirect3DVolume9 *self), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DSwapChain9(X) \
    X(IDirect3DSwapChain9, 0, QueryInterface, HRESULT, (IDirect3DSwapChain9 *self, REFIID riid, void **ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DSwapChain9, 1, AddRef, ULONG, (IDirect3DSwapChain9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DSwapChain9, 2, Release, ULONG, (IDirect3DSwapChain9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DSwapChain9, 3, Present, HRESULT, (IDirect3DSwapChain9 *self, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSwapChain9, 4, GetFrontBufferData, HRESULT, (IDirect3DSwapChain9 *self, struct IDirect3DSurface9 *pDestSurface), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSwapChain9, 5, GetBackBuffer, HRESULT, (IDirect3DSwapChain9 *self, UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, struct IDirect3DSurface9 **ppBackBuffer), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSwapChain9, 6, GetRasterStatus, HRESULT, (IDirect3DSwapChain9 *self, D3DRASTER_STATUS *pRasterStatus), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSwapChain9, 7, GetDisplayMode, HRESULT, (IDirect3DSwapChain9 *self, D3DDISPLAYMODE *pMode), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSwapChain9, 8, GetDevice, HRESULT, (IDirect3DSwapChain9 *self, struct IDirect3DDevice9 **ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSwapChain9, 9, GetPresentParameters, HRESULT, (IDirect3DSwapChain9 *self, D3DPRESENT_PARAMETERS *pPresentationParameters), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DResource9(X) \
    X(IDirect3DResource9, 0, QueryInterface, HRESULT, (IDirect3DResource9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DResource9, 1, AddRef, ULONG, (IDirect3DResource9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DResource9, 2, Release, ULONG, (IDirect3DResource9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DResource9, 3, GetDevice, HRESULT, (IDirect3DResource9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DResource9, 4, SetPrivateData, HRESULT, (IDirect3DResource9 *self, REFGUID guid, const void *data, DWORD data_size, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DResource9, 5, GetPrivateData, HRESULT, (IDirect3DResource9 *self, REFGUID refguid, void* pData, DWORD* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DResource9, 6, FreePrivateData, HRESULT, (IDirect3DResource9 *self, REFGUID refguid), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DResource9, 7, SetPriority, DWORD, (IDirect3DResource9 *self, DWORD PriorityNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DResource9, 8, GetPriority, DWORD, (IDirect3DResource9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DResource9, 9, PreLoad, void, (IDirect3DResource9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DResource9, 10, GetType, D3DRESOURCETYPE, (IDirect3DResource9 *self), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DSurface9(X) \
    X(IDirect3DSurface9, 0, QueryInterface, HRESULT, (IDirect3DSurface9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DSurface9, 1, AddRef, ULONG, (IDirect3DSurface9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DSurface9, 2, Release, ULONG, (IDirect3DSurface9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DSurface9, 3, GetDevice, HRESULT, (IDirect3DSurface9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 4, SetPrivateData, HRESULT, (IDirect3DSurface9 *self, REFGUID guid, const void *data, DWORD data_size, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 5, GetPrivateData, HRESULT, (IDirect3DSurface9 *self, REFGUID refguid, void* pData, DWORD* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 6, FreePrivateData, HRESULT, (IDirect3DSurface9 *self, REFGUID refguid), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 7, SetPriority, DWORD, (IDirect3DSurface9 *self, DWORD PriorityNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 8, GetPriority, DWORD, (IDirect3DSurface9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 9, PreLoad, void, (IDirect3DSurface9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 10, GetType, D3DRESOURCETYPE, (IDirect3DSurface9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 11, GetContainer, HRESULT, (IDirect3DSurface9 *self, REFIID riid, void** ppContainer), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 12, GetDesc, HRESULT, (IDirect3DSurface9 *self, D3DSURFACE_DESC* pDesc), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 13, LockRect, HRESULT, (IDirect3DSurface9 *self, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 14, UnlockRect, HRESULT, (IDirect3DSurface9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 15, GetDC, HRESULT, (IDirect3DSurface9 *self, HDC* phdc), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DSurface9, 16, ReleaseDC, HRESULT, (IDirect3DSurface9 *self, HDC hdc), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DVertexBuffer9(X) \
    X(IDirect3DVertexBuffer9, 0, QueryInterface, HRESULT, (IDirect3DVertexBuffer9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVertexBuffer9, 1, AddRef, ULONG, (IDirect3DVertexBuffer9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVertexBuffer9, 2, Release, ULONG, (IDirect3DVertexBuffer9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVertexBuffer9, 3, GetDevice, HRESULT, (IDirect3DVertexBuffer9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 4, SetPrivateData, HRESULT, (IDirect3DVertexBuffer9 *self, REFGUID guid, const void *data, DWORD data_size, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 5, GetPrivateData, HRESULT, (IDirect3DVertexBuffer9 *self, REFGUID refguid, void* pData, DWORD* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 6, FreePrivateData, HRESULT, (IDirect3DVertexBuffer9 *self, REFGUID refguid), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 7, SetPriority, DWORD, (IDirect3DVertexBuffer9 *self, DWORD PriorityNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 8, GetPriority, DWORD, (IDirect3DVertexBuffer9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 9, PreLoad, void, (IDirect3DVertexBuffer9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 10, GetType, D3DRESOURCETYPE, (IDirect3DVertexBuffer9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 11, Lock, HRESULT, (IDirect3DVertexBuffer9 *self, UINT OffsetToLock, UINT SizeToLock, void** ppbData, DWORD Flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 12, Unlock, HRESULT, (IDirect3DVertexBuffer9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexBuffer9, 13, GetDesc, HRESULT, (IDirect3DVertexBuffer9 *self, D3DVERTEXBUFFER_DESC* pDesc), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DIndexBuffer9(X) \
    X(IDirect3DIndexBuffer9, 0, QueryInterface, HRESULT, (IDirect3DIndexBuffer9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DIndexBuffer9, 1, AddRef, ULONG, (IDirect3DIndexBuffer9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DIndexBuffer9, 2, Release, ULONG, (IDirect3DIndexBuffer9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DIndexBuffer9, 3, GetDevice, HRESULT, (IDirect3DIndexBuffer9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 4, SetPrivateData, HRESULT, (IDirect3DIndexBuffer9 *self, REFGUID guid, const void *data, DWORD data_size, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 5, GetPrivateData, HRESULT, (IDirect3DIndexBuffer9 *self, REFGUID refguid, void* pData, DWORD* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 6, FreePrivateData, HRESULT, (IDirect3DIndexBuffer9 *self, REFGUID refguid), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 7, SetPriority, DWORD, (IDirect3DIndexBuffer9 *self, DWORD PriorityNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 8, GetPriority, DWORD, (IDirect3DIndexBuffer9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 9, PreLoad, void, (IDirect3DIndexBuffer9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 10, GetType, D3DRESOURCETYPE, (IDirect3DIndexBuffer9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 11, Lock, HRESULT, (IDirect3DIndexBuffer9 *self, UINT OffsetToLock, UINT SizeToLock, void** ppbData, DWORD Flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 12, Unlock, HRESULT, (IDirect3DIndexBuffer9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DIndexBuffer9, 13, GetDesc, HRESULT, (IDirect3DIndexBuffer9 *self, D3DINDEXBUFFER_DESC* pDesc), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DBaseTexture9(X) \
    X(IDirect3DBaseTexture9, 0, QueryInterface, HRESULT, (IDirect3DBaseTexture9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DBaseTexture9, 1, AddRef, ULONG, (IDirect3DBaseTexture9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DBaseTexture9, 2, Release, ULONG, (IDirect3DBaseTexture9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DBaseTexture9, 3, GetDevice, HRESULT, (IDirect3DBaseTexture9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 4, SetPrivateData, HRESULT, (IDirect3DBaseTexture9 *self, REFGUID guid, const void *data, DWORD data_size, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 5, GetPrivateData, HRESULT, (IDirect3DBaseTexture9 *self, REFGUID refguid, void* pData, DWORD* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 6, FreePrivateData, HRESULT, (IDirect3DBaseTexture9 *self, REFGUID refguid), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 7, SetPriority, DWORD, (IDirect3DBaseTexture9 *self, DWORD PriorityNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 8, GetPriority, DWORD, (IDirect3DBaseTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 9, PreLoad, void, (IDirect3DBaseTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 10, GetType, D3DRESOURCETYPE, (IDirect3DBaseTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 11, SetLOD, DWORD, (IDirect3DBaseTexture9 *self, DWORD LODNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 12, GetLOD, DWORD, (IDirect3DBaseTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 13, GetLevelCount, DWORD, (IDirect3DBaseTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 14, SetAutoGenFilterType, HRESULT, (IDirect3DBaseTexture9 *self, D3DTEXTUREFILTERTYPE FilterType), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 15, GetAutoGenFilterType, D3DTEXTUREFILTERTYPE, (IDirect3DBaseTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DBaseTexture9, 16, GenerateMipSubLevels, void, (IDirect3DBaseTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DCubeTexture9(X) \
    X(IDirect3DCubeTexture9, 0, QueryInterface, HRESULT, (IDirect3DCubeTexture9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DCubeTexture9, 1, AddRef, ULONG, (IDirect3DCubeTexture9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DCubeTexture9, 2, Release, ULONG, (IDirect3DCubeTexture9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DCubeTexture9, 3, GetDevice, HRESULT, (IDirect3DCubeTexture9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 4, SetPrivateData, HRESULT, (IDirect3DCubeTexture9 *self, REFGUID guid, const void *data, DWORD data_size, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 5, GetPrivateData, HRESULT, (IDirect3DCubeTexture9 *self, REFGUID refguid, void* pData, DWORD* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 6, FreePrivateData, HRESULT, (IDirect3DCubeTexture9 *self, REFGUID refguid), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 7, SetPriority, DWORD, (IDirect3DCubeTexture9 *self, DWORD PriorityNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 8, GetPriority, DWORD, (IDirect3DCubeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 9, PreLoad, void, (IDirect3DCubeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 10, GetType, D3DRESOURCETYPE, (IDirect3DCubeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 11, SetLOD, DWORD, (IDirect3DCubeTexture9 *self, DWORD LODNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 12, GetLOD, DWORD, (IDirect3DCubeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 13, GetLevelCount, DWORD, (IDirect3DCubeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 14, SetAutoGenFilterType, HRESULT, (IDirect3DCubeTexture9 *self, D3DTEXTUREFILTERTYPE FilterType), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 15, GetAutoGenFilterType, D3DTEXTUREFILTERTYPE, (IDirect3DCubeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 16, GenerateMipSubLevels, void, (IDirect3DCubeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 17, GetLevelDesc, HRESULT, (IDirect3DCubeTexture9 *self, UINT Level,D3DSURFACE_DESC* pDesc), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 18, GetCubeMapSurface, HRESULT, (IDirect3DCubeTexture9 *self, D3DCUBEMAP_FACES FaceType, UINT Level, IDirect3DSurface9** ppCubeMapSurface), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 19, LockRect, HRESULT, (IDirect3DCubeTexture9 *self, D3DCUBEMAP_FACES face, UINT level, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 20, UnlockRect, HRESULT, (IDirect3DCubeTexture9 *self, D3DCUBEMAP_FACES FaceType, UINT Level), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DCubeTexture9, 21, AddDirtyRect, HRESULT, (IDirect3DCubeTexture9 *self, D3DCUBEMAP_FACES face, const RECT *dirty_rect), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DTexture9(X) \
    X(IDirect3DTexture9, 0, QueryInterface, HRESULT, (IDirect3DTexture9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DTexture9, 1, AddRef, ULONG, (IDirect3DTexture9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DTexture9, 2, Release, ULONG, (IDirect3DTexture9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DTexture9, 3, GetDevice, HRESULT, (IDirect3DTexture9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 4, SetPrivateData, HRESULT, (IDirect3DTexture9 *self, REFGUID guid, const void *data, DWORD data_size, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 5, GetPrivateData, HRESULT, (IDirect3DTexture9 *self, REFGUID refguid, void* pData, DWORD* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 6, FreePrivateData, HRESULT, (IDirect3DTexture9 *self, REFGUID refguid), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 7, SetPriority, DWORD, (IDirect3DTexture9 *self, DWORD PriorityNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 8, GetPriority, DWORD, (IDirect3DTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 9, PreLoad, void, (IDirect3DTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 10, GetType, D3DRESOURCETYPE, (IDirect3DTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 11, SetLOD, DWORD, (IDirect3DTexture9 *self, DWORD LODNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 12, GetLOD, DWORD, (IDirect3DTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 13, GetLevelCount, DWORD, (IDirect3DTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 14, SetAutoGenFilterType, HRESULT, (IDirect3DTexture9 *self, D3DTEXTUREFILTERTYPE FilterType), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 15, GetAutoGenFilterType, D3DTEXTUREFILTERTYPE, (IDirect3DTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 16, GenerateMipSubLevels, void, (IDirect3DTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 17, GetLevelDesc, HRESULT, (IDirect3DTexture9 *self, UINT Level, D3DSURFACE_DESC* pDesc), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 18, GetSurfaceLevel, HRESULT, (IDirect3DTexture9 *self, UINT Level, IDirect3DSurface9** ppSurfaceLevel), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 19, LockRect, HRESULT, (IDirect3DTexture9 *self, UINT level, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 20, UnlockRect, HRESULT, (IDirect3DTexture9 *self, UINT Level), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DTexture9, 21, AddDirtyRect, HRESULT, (IDirect3DTexture9 *self, const RECT *dirty_rect), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DVolumeTexture9(X) \
    X(IDirect3DVolumeTexture9, 0, QueryInterface, HRESULT, (IDirect3DVolumeTexture9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVolumeTexture9, 1, AddRef, ULONG, (IDirect3DVolumeTexture9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVolumeTexture9, 2, Release, ULONG, (IDirect3DVolumeTexture9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVolumeTexture9, 3, GetDevice, HRESULT, (IDirect3DVolumeTexture9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 4, SetPrivateData, HRESULT, (IDirect3DVolumeTexture9 *self, REFGUID guid, const void *data, DWORD data_size, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 5, GetPrivateData, HRESULT, (IDirect3DVolumeTexture9 *self, REFGUID refguid, void* pData, DWORD* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 6, FreePrivateData, HRESULT, (IDirect3DVolumeTexture9 *self, REFGUID refguid), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 7, SetPriority, DWORD, (IDirect3DVolumeTexture9 *self, DWORD PriorityNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 8, GetPriority, DWORD, (IDirect3DVolumeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 9, PreLoad, void, (IDirect3DVolumeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 10, GetType, D3DRESOURCETYPE, (IDirect3DVolumeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 11, SetLOD, DWORD, (IDirect3DVolumeTexture9 *self, DWORD LODNew), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 12, GetLOD, DWORD, (IDirect3DVolumeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 13, GetLevelCount, DWORD, (IDirect3DVolumeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 14, SetAutoGenFilterType, HRESULT, (IDirect3DVolumeTexture9 *self, D3DTEXTUREFILTERTYPE FilterType), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 15, GetAutoGenFilterType, D3DTEXTUREFILTERTYPE, (IDirect3DVolumeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 16, GenerateMipSubLevels, void, (IDirect3DVolumeTexture9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 17, GetLevelDesc, HRESULT, (IDirect3DVolumeTexture9 *self, UINT Level, D3DVOLUME_DESC *pDesc), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 18, GetVolumeLevel, HRESULT, (IDirect3DVolumeTexture9 *self, UINT Level, IDirect3DVolume9** ppVolumeLevel), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 19, LockBox, HRESULT, (IDirect3DVolumeTexture9 *self, UINT level, D3DLOCKED_BOX *locked_box, const D3DBOX *box, DWORD flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 20, UnlockBox, HRESULT, (IDirect3DVolumeTexture9 *self, UINT Level), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVolumeTexture9, 21, AddDirtyBox, HRESULT, (IDirect3DVolumeTexture9 *self, const D3DBOX *dirty_box), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DVertexDeclaration9(X) \
    X(IDirect3DVertexDeclaration9, 0, QueryInterface, HRESULT, (IDirect3DVertexDeclaration9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVertexDeclaration9, 1, AddRef, ULONG, (IDirect3DVertexDeclaration9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVertexDeclaration9, 2, Release, ULONG, (IDirect3DVertexDeclaration9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVertexDeclaration9, 3, GetDevice, HRESULT, (IDirect3DVertexDeclaration9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexDeclaration9, 4, GetDeclaration, HRESULT, (IDirect3DVertexDeclaration9 *self, D3DVERTEXELEMENT9*, UINT* pNumElements), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DVertexShader9(X) \
    X(IDirect3DVertexShader9, 0, QueryInterface, HRESULT, (IDirect3DVertexShader9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVertexShader9, 1, AddRef, ULONG, (IDirect3DVertexShader9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVertexShader9, 2, Release, ULONG, (IDirect3DVertexShader9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DVertexShader9, 3, GetDevice, HRESULT, (IDirect3DVertexShader9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DVertexShader9, 4, GetFunction, HRESULT, (IDirect3DVertexShader9 *self, void*, UINT* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DPixelShader9(X) \
    X(IDirect3DPixelShader9, 0, QueryInterface, HRESULT, (IDirect3DPixelShader9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DPixelShader9, 1, AddRef, ULONG, (IDirect3DPixelShader9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DPixelShader9, 2, Release, ULONG, (IDirect3DPixelShader9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DPixelShader9, 3, GetDevice, HRESULT, (IDirect3DPixelShader9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DPixelShader9, 4, GetFunction, HRESULT, (IDirect3DPixelShader9 *self, void*, UINT* pSizeOfData), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DStateBlock9(X) \
    X(IDirect3DStateBlock9, 0, QueryInterface, HRESULT, (IDirect3DStateBlock9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DStateBlock9, 1, AddRef, ULONG, (IDirect3DStateBlock9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DStateBlock9, 2, Release, ULONG, (IDirect3DStateBlock9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DStateBlock9, 3, GetDevice, HRESULT, (IDirect3DStateBlock9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DStateBlock9, 4, Capture, HRESULT, (IDirect3DStateBlock9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DStateBlock9, 5, Apply, HRESULT, (IDirect3DStateBlock9 *self), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DQuery9(X) \
    X(IDirect3DQuery9, 0, QueryInterface, HRESULT, (IDirect3DQuery9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DQuery9, 1, AddRef, ULONG, (IDirect3DQuery9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DQuery9, 2, Release, ULONG, (IDirect3DQuery9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DQuery9, 3, GetDevice, HRESULT, (IDirect3DQuery9 *self, struct IDirect3DDevice9** ppDevice), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DQuery9, 4, GetType, D3DQUERYTYPE, (IDirect3DQuery9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DQuery9, 5, GetDataSize, DWORD, (IDirect3DQuery9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DQuery9, 6, Issue, HRESULT, (IDirect3DQuery9 *self, DWORD dwIssueFlags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DQuery9, 7, GetData, HRESULT, (IDirect3DQuery9 *self, void* pData, DWORD dwSize, DWORD dwGetDataFlags), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_METHODS_IDirect3DDevice9(X) \
    X(IDirect3DDevice9, 0, QueryInterface, HRESULT, (IDirect3DDevice9 *self, REFIID riid, void** ppvObject), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DDevice9, 1, AddRef, ULONG, (IDirect3DDevice9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DDevice9, 2, Release, ULONG, (IDirect3DDevice9 *self), PW_D3D9_POLICY_LOCAL_IDENTITY) \
    X(IDirect3DDevice9, 3, TestCooperativeLevel, HRESULT, (IDirect3DDevice9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 4, GetAvailableTextureMem, UINT, (IDirect3DDevice9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 5, EvictManagedResources, HRESULT, (IDirect3DDevice9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 6, GetDirect3D, HRESULT, (IDirect3DDevice9 *self, IDirect3D9** ppD3D9), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 7, GetDeviceCaps, HRESULT, (IDirect3DDevice9 *self, D3DCAPS9* pCaps), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 8, GetDisplayMode, HRESULT, (IDirect3DDevice9 *self, UINT iSwapChain, D3DDISPLAYMODE* pMode), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 9, GetCreationParameters, HRESULT, (IDirect3DDevice9 *self, D3DDEVICE_CREATION_PARAMETERS *pParameters), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 10, SetCursorProperties, HRESULT, (IDirect3DDevice9 *self, UINT XHotSpot, UINT YHotSpot, IDirect3DSurface9* pCursorBitmap), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 11, SetCursorPosition, void, (IDirect3DDevice9 *self, int X,int Y, DWORD Flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 12, ShowCursor, BOOL, (IDirect3DDevice9 *self, BOOL bShow), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 13, CreateAdditionalSwapChain, HRESULT, (IDirect3DDevice9 *self, D3DPRESENT_PARAMETERS* pPresentationParameters, IDirect3DSwapChain9** pSwapChain), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 14, GetSwapChain, HRESULT, (IDirect3DDevice9 *self, UINT iSwapChain, IDirect3DSwapChain9** pSwapChain), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 15, GetNumberOfSwapChains, UINT, (IDirect3DDevice9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 16, Reset, HRESULT, (IDirect3DDevice9 *self, D3DPRESENT_PARAMETERS* pPresentationParameters), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 17, Present, HRESULT, (IDirect3DDevice9 *self, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 18, GetBackBuffer, HRESULT, (IDirect3DDevice9 *self, UINT iSwapChain, UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface9** ppBackBuffer), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 19, GetRasterStatus, HRESULT, (IDirect3DDevice9 *self, UINT iSwapChain, D3DRASTER_STATUS* pRasterStatus), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 20, SetDialogBoxMode, HRESULT, (IDirect3DDevice9 *self, BOOL bEnableDialogs), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 21, SetGammaRamp, void, (IDirect3DDevice9 *self, UINT swapchain_idx, DWORD flags, const D3DGAMMARAMP *ramp), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 22, GetGammaRamp, void, (IDirect3DDevice9 *self, UINT iSwapChain, D3DGAMMARAMP* pRamp), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 23, CreateTexture, HRESULT, (IDirect3DDevice9 *self, UINT Width, UINT Height, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DTexture9** ppTexture, HANDLE* pSharedHandle), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 24, CreateVolumeTexture, HRESULT, (IDirect3DDevice9 *self, UINT Width, UINT Height, UINT Depth, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DVolumeTexture9** ppVolumeTexture, HANDLE* pSharedHandle), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 25, CreateCubeTexture, HRESULT, (IDirect3DDevice9 *self, UINT EdgeLength, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DCubeTexture9** ppCubeTexture, HANDLE* pSharedHandle), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 26, CreateVertexBuffer, HRESULT, (IDirect3DDevice9 *self, UINT Length, DWORD Usage, DWORD FVF, D3DPOOL Pool, IDirect3DVertexBuffer9** ppVertexBuffer, HANDLE* pSharedHandle), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 27, CreateIndexBuffer, HRESULT, (IDirect3DDevice9 *self, UINT Length, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DIndexBuffer9** ppIndexBuffer, HANDLE* pSharedHandle), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 28, CreateRenderTarget, HRESULT, (IDirect3DDevice9 *self, UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, BOOL Lockable, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 29, CreateDepthStencilSurface, HRESULT, (IDirect3DDevice9 *self, UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, BOOL Discard, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 30, UpdateSurface, HRESULT, (IDirect3DDevice9 *self, IDirect3DSurface9 *src_surface, const RECT *src_rect, IDirect3DSurface9 *dst_surface, const POINT *dst_point), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 31, UpdateTexture, HRESULT, (IDirect3DDevice9 *self, IDirect3DBaseTexture9* pSourceTexture, IDirect3DBaseTexture9* pDestinationTexture), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 32, GetRenderTargetData, HRESULT, (IDirect3DDevice9 *self, IDirect3DSurface9* pRenderTarget, IDirect3DSurface9* pDestSurface), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 33, GetFrontBufferData, HRESULT, (IDirect3DDevice9 *self, UINT iSwapChain, IDirect3DSurface9* pDestSurface), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 34, StretchRect, HRESULT, (IDirect3DDevice9 *self, IDirect3DSurface9 *src_surface, const RECT *src_rect, IDirect3DSurface9 *dst_surface, const RECT *dst_rect, D3DTEXTUREFILTERTYPE filter), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 35, ColorFill, HRESULT, (IDirect3DDevice9 *self, IDirect3DSurface9 *surface, const RECT *rect, D3DCOLOR color), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 36, CreateOffscreenPlainSurface, HRESULT, (IDirect3DDevice9 *self, UINT Width, UINT Height, D3DFORMAT Format, D3DPOOL Pool, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 37, SetRenderTarget, HRESULT, (IDirect3DDevice9 *self, DWORD RenderTargetIndex, IDirect3DSurface9* pRenderTarget), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 38, GetRenderTarget, HRESULT, (IDirect3DDevice9 *self, DWORD RenderTargetIndex, IDirect3DSurface9** ppRenderTarget), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 39, SetDepthStencilSurface, HRESULT, (IDirect3DDevice9 *self, IDirect3DSurface9* pNewZStencil), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 40, GetDepthStencilSurface, HRESULT, (IDirect3DDevice9 *self, IDirect3DSurface9** ppZStencilSurface), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 41, BeginScene, HRESULT, (IDirect3DDevice9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 42, EndScene, HRESULT, (IDirect3DDevice9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 43, Clear, HRESULT, (IDirect3DDevice9 *self, DWORD rect_count, const D3DRECT *rects, DWORD flags, D3DCOLOR color, float z, DWORD stencil), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 44, SetTransform, HRESULT, (IDirect3DDevice9 *self, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 45, GetTransform, HRESULT, (IDirect3DDevice9 *self, D3DTRANSFORMSTATETYPE State, D3DMATRIX* pMatrix), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 46, MultiplyTransform, HRESULT, (IDirect3DDevice9 *self, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 47, SetViewport, HRESULT, (IDirect3DDevice9 *self, const D3DVIEWPORT9 *viewport), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 48, GetViewport, HRESULT, (IDirect3DDevice9 *self, D3DVIEWPORT9* pViewport), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 49, SetMaterial, HRESULT, (IDirect3DDevice9 *self, const D3DMATERIAL9 *material), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 50, GetMaterial, HRESULT, (IDirect3DDevice9 *self, D3DMATERIAL9* pMaterial), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 51, SetLight, HRESULT, (IDirect3DDevice9 *self, DWORD index, const D3DLIGHT9 *light), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 52, GetLight, HRESULT, (IDirect3DDevice9 *self, DWORD Index, D3DLIGHT9*), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 53, LightEnable, HRESULT, (IDirect3DDevice9 *self, DWORD Index, BOOL Enable), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 54, GetLightEnable, HRESULT, (IDirect3DDevice9 *self, DWORD Index, BOOL* pEnable), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 55, SetClipPlane, HRESULT, (IDirect3DDevice9 *self, DWORD index, const float *plane), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 56, GetClipPlane, HRESULT, (IDirect3DDevice9 *self, DWORD Index, float* pPlane), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 57, SetRenderState, HRESULT, (IDirect3DDevice9 *self, D3DRENDERSTATETYPE State, DWORD Value), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 58, GetRenderState, HRESULT, (IDirect3DDevice9 *self, D3DRENDERSTATETYPE State, DWORD* pValue), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 59, CreateStateBlock, HRESULT, (IDirect3DDevice9 *self, D3DSTATEBLOCKTYPE Type, IDirect3DStateBlock9** ppSB), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 60, BeginStateBlock, HRESULT, (IDirect3DDevice9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 61, EndStateBlock, HRESULT, (IDirect3DDevice9 *self, IDirect3DStateBlock9** ppSB), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 62, SetClipStatus, HRESULT, (IDirect3DDevice9 *self, const D3DCLIPSTATUS9 *clip_status), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 63, GetClipStatus, HRESULT, (IDirect3DDevice9 *self, D3DCLIPSTATUS9* pClipStatus), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 64, GetTexture, HRESULT, (IDirect3DDevice9 *self, DWORD Stage, IDirect3DBaseTexture9** ppTexture), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 65, SetTexture, HRESULT, (IDirect3DDevice9 *self, DWORD Stage, IDirect3DBaseTexture9* pTexture), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 66, GetTextureStageState, HRESULT, (IDirect3DDevice9 *self, DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD* pValue), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 67, SetTextureStageState, HRESULT, (IDirect3DDevice9 *self, DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD Value), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 68, GetSamplerState, HRESULT, (IDirect3DDevice9 *self, DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD* pValue), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 69, SetSamplerState, HRESULT, (IDirect3DDevice9 *self, DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD Value), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 70, ValidateDevice, HRESULT, (IDirect3DDevice9 *self, DWORD* pNumPasses), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 71, SetPaletteEntries, HRESULT, (IDirect3DDevice9 *self, UINT palette_idx, const PALETTEENTRY *entries), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 72, GetPaletteEntries, HRESULT, (IDirect3DDevice9 *self, UINT PaletteNumber,PALETTEENTRY* pEntries), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 73, SetCurrentTexturePalette, HRESULT, (IDirect3DDevice9 *self, UINT PaletteNumber), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 74, GetCurrentTexturePalette, HRESULT, (IDirect3DDevice9 *self, UINT *PaletteNumber), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 75, SetScissorRect, HRESULT, (IDirect3DDevice9 *self, const RECT *rect), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 76, GetScissorRect, HRESULT, (IDirect3DDevice9 *self, RECT* pRect), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 77, SetSoftwareVertexProcessing, HRESULT, (IDirect3DDevice9 *self, BOOL bSoftware), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 78, GetSoftwareVertexProcessing, BOOL, (IDirect3DDevice9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 79, SetNPatchMode, HRESULT, (IDirect3DDevice9 *self, float nSegments), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 80, GetNPatchMode, float, (IDirect3DDevice9 *self), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 81, DrawPrimitive, HRESULT, (IDirect3DDevice9 *self, D3DPRIMITIVETYPE PrimitiveType, UINT StartVertex, UINT PrimitiveCount), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 82, DrawIndexedPrimitive, HRESULT, (IDirect3DDevice9 *self, D3DPRIMITIVETYPE, INT BaseVertexIndex, UINT MinVertexIndex, UINT NumVertices, UINT startIndex, UINT primCount), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 83, DrawPrimitiveUP, HRESULT, (IDirect3DDevice9 *self, D3DPRIMITIVETYPE primitive_type, UINT primitive_count, const void *data, UINT stride), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 84, DrawIndexedPrimitiveUP, HRESULT, (IDirect3DDevice9 *self, D3DPRIMITIVETYPE primitive_type, UINT min_vertex_idx, UINT vertex_count, UINT primitive_count, const void *index_data, D3DFORMAT index_format, const void *data, UINT stride), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 85, ProcessVertices, HRESULT, (IDirect3DDevice9 *self, UINT SrcStartIndex, UINT DestIndex, UINT VertexCount, IDirect3DVertexBuffer9* pDestBuffer, IDirect3DVertexDeclaration9* pVertexDecl, DWORD Flags), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 86, CreateVertexDeclaration, HRESULT, (IDirect3DDevice9 *self, const D3DVERTEXELEMENT9 *elements, IDirect3DVertexDeclaration9 **declaration), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 87, SetVertexDeclaration, HRESULT, (IDirect3DDevice9 *self, IDirect3DVertexDeclaration9* pDecl), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 88, GetVertexDeclaration, HRESULT, (IDirect3DDevice9 *self, IDirect3DVertexDeclaration9** ppDecl), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 89, SetFVF, HRESULT, (IDirect3DDevice9 *self, DWORD FVF), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 90, GetFVF, HRESULT, (IDirect3DDevice9 *self, DWORD* pFVF), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 91, CreateVertexShader, HRESULT, (IDirect3DDevice9 *self, const DWORD *byte_code, IDirect3DVertexShader9 **shader), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 92, SetVertexShader, HRESULT, (IDirect3DDevice9 *self, IDirect3DVertexShader9* pShader), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 93, GetVertexShader, HRESULT, (IDirect3DDevice9 *self, IDirect3DVertexShader9** ppShader), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 94, SetVertexShaderConstantF, HRESULT, (IDirect3DDevice9 *self, UINT reg_idx, const float *data, UINT count), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 95, GetVertexShaderConstantF, HRESULT, (IDirect3DDevice9 *self, UINT StartRegister, float* pConstantData, UINT Vector4fCount), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 96, SetVertexShaderConstantI, HRESULT, (IDirect3DDevice9 *self, UINT reg_idx, const int *data, UINT count), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 97, GetVertexShaderConstantI, HRESULT, (IDirect3DDevice9 *self, UINT StartRegister, int* pConstantData, UINT Vector4iCount), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 98, SetVertexShaderConstantB, HRESULT, (IDirect3DDevice9 *self, UINT reg_idx, const BOOL *data, UINT count), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 99, GetVertexShaderConstantB, HRESULT, (IDirect3DDevice9 *self, UINT StartRegister, BOOL* pConstantData, UINT BoolCount), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 100, SetStreamSource, HRESULT, (IDirect3DDevice9 *self, UINT StreamNumber, IDirect3DVertexBuffer9* pStreamData, UINT OffsetInBytes, UINT Stride), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 101, GetStreamSource, HRESULT, (IDirect3DDevice9 *self, UINT StreamNumber, IDirect3DVertexBuffer9** ppStreamData, UINT* OffsetInBytes, UINT* pStride), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 102, SetStreamSourceFreq, HRESULT, (IDirect3DDevice9 *self, UINT StreamNumber, UINT Divider), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 103, GetStreamSourceFreq, HRESULT, (IDirect3DDevice9 *self, UINT StreamNumber, UINT* Divider), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 104, SetIndices, HRESULT, (IDirect3DDevice9 *self, IDirect3DIndexBuffer9* pIndexData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 105, GetIndices, HRESULT, (IDirect3DDevice9 *self, IDirect3DIndexBuffer9** ppIndexData), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 106, CreatePixelShader, HRESULT, (IDirect3DDevice9 *self, const DWORD *byte_code, IDirect3DPixelShader9 **shader), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 107, SetPixelShader, HRESULT, (IDirect3DDevice9 *self, IDirect3DPixelShader9* pShader), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 108, GetPixelShader, HRESULT, (IDirect3DDevice9 *self, IDirect3DPixelShader9** ppShader), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 109, SetPixelShaderConstantF, HRESULT, (IDirect3DDevice9 *self, UINT reg_idx, const float *data, UINT count), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 110, GetPixelShaderConstantF, HRESULT, (IDirect3DDevice9 *self, UINT StartRegister, float* pConstantData, UINT Vector4fCount), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 111, SetPixelShaderConstantI, HRESULT, (IDirect3DDevice9 *self, UINT reg_idx, const int *data, UINT count), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 112, GetPixelShaderConstantI, HRESULT, (IDirect3DDevice9 *self, UINT StartRegister, int* pConstantData, UINT Vector4iCount), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 113, SetPixelShaderConstantB, HRESULT, (IDirect3DDevice9 *self, UINT reg_idx, const BOOL *data, UINT count), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 114, GetPixelShaderConstantB, HRESULT, (IDirect3DDevice9 *self, UINT StartRegister, BOOL* pConstantData, UINT BoolCount), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 115, DrawRectPatch, HRESULT, (IDirect3DDevice9 *self, UINT handle, const float *segment_count, const D3DRECTPATCH_INFO *patch_info), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 116, DrawTriPatch, HRESULT, (IDirect3DDevice9 *self, UINT handle, const float *segment_count, const D3DTRIPATCH_INFO *patch_info), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 117, DeletePatch, HRESULT, (IDirect3DDevice9 *self, UINT Handle), PW_D3D9_POLICY_UNSUPPORTED) \
    X(IDirect3DDevice9, 118, CreateQuery, HRESULT, (IDirect3DDevice9 *self, D3DQUERYTYPE Type, IDirect3DQuery9** ppQuery), PW_D3D9_POLICY_UNSUPPORTED)

#define PW_D3D9_INTERFACES(X) \
    X(IDirect3D9, 17) \
    X(IDirect3DVolume9, 11) \
    X(IDirect3DSwapChain9, 10) \
    X(IDirect3DResource9, 11) \
    X(IDirect3DSurface9, 17) \
    X(IDirect3DVertexBuffer9, 14) \
    X(IDirect3DIndexBuffer9, 14) \
    X(IDirect3DBaseTexture9, 17) \
    X(IDirect3DCubeTexture9, 22) \
    X(IDirect3DTexture9, 22) \
    X(IDirect3DVolumeTexture9, 22) \
    X(IDirect3DVertexDeclaration9, 5) \
    X(IDirect3DVertexShader9, 5) \
    X(IDirect3DPixelShader9, 5) \
    X(IDirect3DStateBlock9, 6) \
    X(IDirect3DQuery9, 8) \
    X(IDirect3DDevice9, 119)
#define PW_D3D9_ALL_METHODS(X) \
    PW_D3D9_METHODS_IDirect3D9(X) \
    PW_D3D9_METHODS_IDirect3DVolume9(X) \
    PW_D3D9_METHODS_IDirect3DSwapChain9(X) \
    PW_D3D9_METHODS_IDirect3DResource9(X) \
    PW_D3D9_METHODS_IDirect3DSurface9(X) \
    PW_D3D9_METHODS_IDirect3DVertexBuffer9(X) \
    PW_D3D9_METHODS_IDirect3DIndexBuffer9(X) \
    PW_D3D9_METHODS_IDirect3DBaseTexture9(X) \
    PW_D3D9_METHODS_IDirect3DCubeTexture9(X) \
    PW_D3D9_METHODS_IDirect3DTexture9(X) \
    PW_D3D9_METHODS_IDirect3DVolumeTexture9(X) \
    PW_D3D9_METHODS_IDirect3DVertexDeclaration9(X) \
    PW_D3D9_METHODS_IDirect3DVertexShader9(X) \
    PW_D3D9_METHODS_IDirect3DPixelShader9(X) \
    PW_D3D9_METHODS_IDirect3DStateBlock9(X) \
    PW_D3D9_METHODS_IDirect3DQuery9(X) \
    PW_D3D9_METHODS_IDirect3DDevice9(X)
#endif
