# SPDX-License-Identifier: LGPL-2.1-or-later
@ stdcall BTCpuGetBopCode()
@ stdcall BTCpuGetContext(long long ptr ptr)
@ stdcall BTCpuIsProcessorFeaturePresent(long)
@ stdcall BTCpuProcessInit()
@ stdcall BTCpuThreadInit()
@ stdcall BTCpuResetToConsistentState(ptr)
@ stdcall BTCpuSetContext(long long ptr ptr)
@ stdcall BTCpuSimulate()
@ stdcall BTCpuFlushInstructionCache2(ptr long)
@ stdcall BTCpuFlushInstructionCacheHeavy(ptr long)
@ stdcall BTCpuNotifyMemoryFree(ptr long long long long)
@ stdcall BTCpuNotifyMemoryProtect(ptr long long long long)
@ stdcall BTCpuNotifyUnmapViewOfSection(ptr long long)
@ stdcall BTCpuThreadTerm(long long)
@ stdcall __wine_get_unix_opcode()
