/* SPDX-License-Identifier: LGPL-2.1-or-later */
/* The RADV entry points the profile times, generated from Vulkan header
 * 354's PFN_vk* typedefs for the device functions DXVK 2.6.2 calls.
 * PW_VK_RADV_FN: a value-returning function with a generic wrapper;
 * PW_VK_RADV_FN_VOID: a void one; PW_VK_RADV_FN_HAND: a function whose
 * wrapper is hand-written in pw_vk_radv_profile_wrap.c because its
 * event line describes an argument. Order is the log's function id. */
PW_VK_RADV_FN_VOID(vkCmdDraw, (VkCommandBuffer commandBuffer, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance), (commandBuffer, vertexCount, instanceCount, firstVertex, firstInstance))
PW_VK_RADV_FN_VOID(vkCmdDrawIndexed, (VkCommandBuffer commandBuffer, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t vertexOffset, uint32_t firstInstance), (commandBuffer, indexCount, instanceCount, firstIndex, vertexOffset, firstInstance))
PW_VK_RADV_FN_VOID(vkCmdDrawIndirect, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, uint32_t drawCount, uint32_t stride), (commandBuffer, buffer, offset, drawCount, stride))
PW_VK_RADV_FN_VOID(vkCmdDrawIndexedIndirect, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, uint32_t drawCount, uint32_t stride), (commandBuffer, buffer, offset, drawCount, stride))
PW_VK_RADV_FN_VOID(vkCmdDrawIndirectCount, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkBuffer countBuffer, VkDeviceSize countBufferOffset, uint32_t maxDrawCount, uint32_t stride), (commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride))
PW_VK_RADV_FN_VOID(vkCmdDrawIndexedIndirectCount, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkBuffer countBuffer, VkDeviceSize countBufferOffset, uint32_t maxDrawCount, uint32_t stride), (commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride))
PW_VK_RADV_FN_VOID(vkCmdDrawMultiEXT, (VkCommandBuffer commandBuffer, uint32_t drawCount, const VkMultiDrawInfoEXT* pVertexInfo, uint32_t instanceCount, uint32_t firstInstance, uint32_t stride), (commandBuffer, drawCount, pVertexInfo, instanceCount, firstInstance, stride))
PW_VK_RADV_FN_VOID(vkCmdDrawMultiIndexedEXT, (VkCommandBuffer commandBuffer, uint32_t drawCount, const VkMultiDrawIndexedInfoEXT* pIndexInfo, uint32_t instanceCount, uint32_t firstInstance, uint32_t stride, const int32_t* pVertexOffset), (commandBuffer, drawCount, pIndexInfo, instanceCount, firstInstance, stride, pVertexOffset))
PW_VK_RADV_FN_VOID(vkCmdDrawIndirectByteCountEXT, (VkCommandBuffer commandBuffer, uint32_t instanceCount, uint32_t firstInstance, VkBuffer counterBuffer, VkDeviceSize counterBufferOffset, uint32_t counterOffset, uint32_t vertexStride), (commandBuffer, instanceCount, firstInstance, counterBuffer, counterBufferOffset, counterOffset, vertexStride))
PW_VK_RADV_FN_VOID(vkCmdDispatch, (VkCommandBuffer commandBuffer, uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ), (commandBuffer, groupCountX, groupCountY, groupCountZ))
PW_VK_RADV_FN_VOID(vkCmdDispatchIndirect, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset), (commandBuffer, buffer, offset))
PW_VK_RADV_FN_VOID(vkCmdBindPipeline, (VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipeline pipeline), (commandBuffer, pipelineBindPoint, pipeline))
PW_VK_RADV_FN_VOID(vkCmdBindDescriptorSets, (VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipelineLayout layout, uint32_t firstSet, uint32_t descriptorSetCount, const VkDescriptorSet* pDescriptorSets, uint32_t dynamicOffsetCount, const uint32_t* pDynamicOffsets), (commandBuffer, pipelineBindPoint, layout, firstSet, descriptorSetCount, pDescriptorSets, dynamicOffsetCount, pDynamicOffsets))
PW_VK_RADV_FN_VOID(vkCmdPushConstants, (VkCommandBuffer commandBuffer, VkPipelineLayout layout, VkShaderStageFlags stageFlags, uint32_t offset, uint32_t size, const void* pValues), (commandBuffer, layout, stageFlags, offset, size, pValues))
PW_VK_RADV_FN_VOID(vkCmdBindVertexBuffers, (VkCommandBuffer commandBuffer, uint32_t firstBinding, uint32_t bindingCount, const VkBuffer* pBuffers, const VkDeviceSize* pOffsets), (commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets))
PW_VK_RADV_FN_VOID(vkCmdBindVertexBuffers2, (VkCommandBuffer commandBuffer, uint32_t firstBinding, uint32_t bindingCount, const VkBuffer* pBuffers, const VkDeviceSize* pOffsets, const VkDeviceSize* pSizes, const VkDeviceSize* pStrides), (commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets, pSizes, pStrides))
PW_VK_RADV_FN_VOID(vkCmdBindIndexBuffer, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkIndexType indexType), (commandBuffer, buffer, offset, indexType))
PW_VK_RADV_FN_VOID(vkCmdBindIndexBuffer2KHR, (VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkDeviceSize size, VkIndexType indexType), (commandBuffer, buffer, offset, size, indexType))
PW_VK_RADV_FN_VOID(vkCmdBindTransformFeedbackBuffersEXT, (VkCommandBuffer commandBuffer, uint32_t firstBinding, uint32_t bindingCount, const VkBuffer* pBuffers, const VkDeviceSize* pOffsets, const VkDeviceSize* pSizes), (commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets, pSizes))
PW_VK_RADV_FN_VOID(vkCmdBeginTransformFeedbackEXT, (VkCommandBuffer commandBuffer, uint32_t firstCounterBuffer, uint32_t counterBufferCount, const VkBuffer* pCounterBuffers, const VkDeviceSize* pCounterBufferOffsets), (commandBuffer, firstCounterBuffer, counterBufferCount, pCounterBuffers, pCounterBufferOffsets))
PW_VK_RADV_FN_VOID(vkCmdEndTransformFeedbackEXT, (VkCommandBuffer commandBuffer, uint32_t firstCounterBuffer, uint32_t counterBufferCount, const VkBuffer* pCounterBuffers, const VkDeviceSize* pCounterBufferOffsets), (commandBuffer, firstCounterBuffer, counterBufferCount, pCounterBuffers, pCounterBufferOffsets))
PW_VK_RADV_FN_VOID(vkCmdSetViewport, (VkCommandBuffer commandBuffer, uint32_t firstViewport, uint32_t viewportCount, const VkViewport* pViewports), (commandBuffer, firstViewport, viewportCount, pViewports))
PW_VK_RADV_FN_VOID(vkCmdSetScissor, (VkCommandBuffer commandBuffer, uint32_t firstScissor, uint32_t scissorCount, const VkRect2D* pScissors), (commandBuffer, firstScissor, scissorCount, pScissors))
PW_VK_RADV_FN_VOID(vkCmdSetViewportWithCount, (VkCommandBuffer commandBuffer, uint32_t viewportCount, const VkViewport* pViewports), (commandBuffer, viewportCount, pViewports))
PW_VK_RADV_FN_VOID(vkCmdSetScissorWithCount, (VkCommandBuffer commandBuffer, uint32_t scissorCount, const VkRect2D* pScissors), (commandBuffer, scissorCount, pScissors))
PW_VK_RADV_FN_VOID(vkCmdSetBlendConstants, (VkCommandBuffer commandBuffer, const float blendConstants[4]), (commandBuffer, blendConstants))
PW_VK_RADV_FN_VOID(vkCmdSetDepthBias, (VkCommandBuffer commandBuffer, float depthBiasConstantFactor, float depthBiasClamp, float depthBiasSlopeFactor), (commandBuffer, depthBiasConstantFactor, depthBiasClamp, depthBiasSlopeFactor))
PW_VK_RADV_FN_VOID(vkCmdSetDepthBias2EXT, (VkCommandBuffer commandBuffer, const VkDepthBiasInfoEXT* pDepthBiasInfo), (commandBuffer, pDepthBiasInfo))
PW_VK_RADV_FN_VOID(vkCmdSetDepthBiasEnable, (VkCommandBuffer commandBuffer, VkBool32 depthBiasEnable), (commandBuffer, depthBiasEnable))
PW_VK_RADV_FN_VOID(vkCmdSetDepthBounds, (VkCommandBuffer commandBuffer, float minDepthBounds, float maxDepthBounds), (commandBuffer, minDepthBounds, maxDepthBounds))
PW_VK_RADV_FN_VOID(vkCmdSetDepthBoundsTestEnable, (VkCommandBuffer commandBuffer, VkBool32 depthBoundsTestEnable), (commandBuffer, depthBoundsTestEnable))
PW_VK_RADV_FN_VOID(vkCmdSetDepthClipEnableEXT, (VkCommandBuffer commandBuffer, VkBool32 depthClipEnable), (commandBuffer, depthClipEnable))
PW_VK_RADV_FN_VOID(vkCmdSetDepthCompareOp, (VkCommandBuffer commandBuffer, VkCompareOp depthCompareOp), (commandBuffer, depthCompareOp))
PW_VK_RADV_FN_VOID(vkCmdSetDepthTestEnable, (VkCommandBuffer commandBuffer, VkBool32 depthTestEnable), (commandBuffer, depthTestEnable))
PW_VK_RADV_FN_VOID(vkCmdSetDepthWriteEnable, (VkCommandBuffer commandBuffer, VkBool32 depthWriteEnable), (commandBuffer, depthWriteEnable))
PW_VK_RADV_FN_VOID(vkCmdSetStencilCompareMask, (VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, uint32_t compareMask), (commandBuffer, faceMask, compareMask))
PW_VK_RADV_FN_VOID(vkCmdSetStencilOp, (VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, VkStencilOp failOp, VkStencilOp passOp, VkStencilOp depthFailOp, VkCompareOp compareOp), (commandBuffer, faceMask, failOp, passOp, depthFailOp, compareOp))
PW_VK_RADV_FN_VOID(vkCmdSetStencilReference, (VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, uint32_t reference), (commandBuffer, faceMask, reference))
PW_VK_RADV_FN_VOID(vkCmdSetStencilTestEnable, (VkCommandBuffer commandBuffer, VkBool32 stencilTestEnable), (commandBuffer, stencilTestEnable))
PW_VK_RADV_FN_VOID(vkCmdSetStencilWriteMask, (VkCommandBuffer commandBuffer, VkStencilFaceFlags faceMask, uint32_t writeMask), (commandBuffer, faceMask, writeMask))
PW_VK_RADV_FN_VOID(vkCmdSetCullMode, (VkCommandBuffer commandBuffer, VkCullModeFlags cullMode), (commandBuffer, cullMode))
PW_VK_RADV_FN_VOID(vkCmdSetFrontFace, (VkCommandBuffer commandBuffer, VkFrontFace frontFace), (commandBuffer, frontFace))
PW_VK_RADV_FN_VOID(vkCmdSetPrimitiveTopology, (VkCommandBuffer commandBuffer, VkPrimitiveTopology primitiveTopology), (commandBuffer, primitiveTopology))
PW_VK_RADV_FN_VOID(vkCmdSetPrimitiveRestartEnable, (VkCommandBuffer commandBuffer, VkBool32 primitiveRestartEnable), (commandBuffer, primitiveRestartEnable))
PW_VK_RADV_FN_VOID(vkCmdSetRasterizerDiscardEnable, (VkCommandBuffer commandBuffer, VkBool32 rasterizerDiscardEnable), (commandBuffer, rasterizerDiscardEnable))
PW_VK_RADV_FN_VOID(vkCmdSetRasterizationSamplesEXT, (VkCommandBuffer commandBuffer, VkSampleCountFlagBits rasterizationSamples), (commandBuffer, rasterizationSamples))
PW_VK_RADV_FN_VOID(vkCmdSetSampleMaskEXT, (VkCommandBuffer commandBuffer, VkSampleCountFlagBits samples, const VkSampleMask* pSampleMask), (commandBuffer, samples, pSampleMask))
PW_VK_RADV_FN_VOID(vkCmdSetAlphaToCoverageEnableEXT, (VkCommandBuffer commandBuffer, VkBool32 alphaToCoverageEnable), (commandBuffer, alphaToCoverageEnable))
PW_VK_RADV_FN_VOID(vkCmdSetLineWidth, (VkCommandBuffer commandBuffer, float lineWidth), (commandBuffer, lineWidth))
PW_VK_RADV_FN_VOID(vkCmdPipelineBarrier, (VkCommandBuffer commandBuffer, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, VkDependencyFlags dependencyFlags, uint32_t memoryBarrierCount, const VkMemoryBarrier* pMemoryBarriers, uint32_t bufferMemoryBarrierCount, const VkBufferMemoryBarrier* pBufferMemoryBarriers, uint32_t imageMemoryBarrierCount, const VkImageMemoryBarrier* pImageMemoryBarriers), (commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers))
PW_VK_RADV_FN_VOID(vkCmdPipelineBarrier2, (VkCommandBuffer commandBuffer, const VkDependencyInfo* pDependencyInfo), (commandBuffer, pDependencyInfo))
PW_VK_RADV_FN_VOID(vkCmdSetEvent2, (VkCommandBuffer commandBuffer, VkEvent event, const VkDependencyInfo* pDependencyInfo), (commandBuffer, event, pDependencyInfo))
PW_VK_RADV_FN_VOID(vkCmdWaitEvents2, (VkCommandBuffer commandBuffer, uint32_t eventCount, const VkEvent* pEvents, const VkDependencyInfo* pDependencyInfos), (commandBuffer, eventCount, pEvents, pDependencyInfos))
PW_VK_RADV_FN_VOID(vkCmdResetEvent2, (VkCommandBuffer commandBuffer, VkEvent event, VkPipelineStageFlags2 stageMask), (commandBuffer, event, stageMask))
PW_VK_RADV_FN_VOID(vkCmdBeginRendering, (VkCommandBuffer commandBuffer, const VkRenderingInfo* pRenderingInfo), (commandBuffer, pRenderingInfo))
PW_VK_RADV_FN_VOID(vkCmdEndRendering, (VkCommandBuffer commandBuffer), (commandBuffer))
PW_VK_RADV_FN_VOID(vkCmdBeginRenderPass, (VkCommandBuffer commandBuffer, const VkRenderPassBeginInfo* pRenderPassBegin, VkSubpassContents contents), (commandBuffer, pRenderPassBegin, contents))
PW_VK_RADV_FN_VOID(vkCmdEndRenderPass, (VkCommandBuffer commandBuffer), (commandBuffer))
PW_VK_RADV_FN_VOID(vkCmdClearAttachments, (VkCommandBuffer commandBuffer, uint32_t attachmentCount, const VkClearAttachment* pAttachments, uint32_t rectCount, const VkClearRect* pRects), (commandBuffer, attachmentCount, pAttachments, rectCount, pRects))
PW_VK_RADV_FN_VOID(vkCmdClearColorImage, (VkCommandBuffer commandBuffer, VkImage image, VkImageLayout imageLayout, const VkClearColorValue* pColor, uint32_t rangeCount, const VkImageSubresourceRange* pRanges), (commandBuffer, image, imageLayout, pColor, rangeCount, pRanges))
PW_VK_RADV_FN_VOID(vkCmdClearDepthStencilImage, (VkCommandBuffer commandBuffer, VkImage image, VkImageLayout imageLayout, const VkClearDepthStencilValue* pDepthStencil, uint32_t rangeCount, const VkImageSubresourceRange* pRanges), (commandBuffer, image, imageLayout, pDepthStencil, rangeCount, pRanges))
PW_VK_RADV_FN_VOID(vkCmdCopyBuffer, (VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkBuffer dstBuffer, uint32_t regionCount, const VkBufferCopy* pRegions), (commandBuffer, srcBuffer, dstBuffer, regionCount, pRegions))
PW_VK_RADV_FN_VOID(vkCmdCopyBuffer2, (VkCommandBuffer commandBuffer, const VkCopyBufferInfo2* pCopyBufferInfo), (commandBuffer, pCopyBufferInfo))
PW_VK_RADV_FN_VOID(vkCmdCopyImage, (VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkImageCopy* pRegions), (commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions))
PW_VK_RADV_FN_VOID(vkCmdCopyImage2, (VkCommandBuffer commandBuffer, const VkCopyImageInfo2* pCopyImageInfo), (commandBuffer, pCopyImageInfo))
PW_VK_RADV_FN_VOID(vkCmdCopyBufferToImage, (VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkBufferImageCopy* pRegions), (commandBuffer, srcBuffer, dstImage, dstImageLayout, regionCount, pRegions))
PW_VK_RADV_FN_VOID(vkCmdCopyBufferToImage2, (VkCommandBuffer commandBuffer, const VkCopyBufferToImageInfo2* pCopyBufferToImageInfo), (commandBuffer, pCopyBufferToImageInfo))
PW_VK_RADV_FN_VOID(vkCmdCopyImageToBuffer, (VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkBuffer dstBuffer, uint32_t regionCount, const VkBufferImageCopy* pRegions), (commandBuffer, srcImage, srcImageLayout, dstBuffer, regionCount, pRegions))
PW_VK_RADV_FN_VOID(vkCmdCopyImageToBuffer2, (VkCommandBuffer commandBuffer, const VkCopyImageToBufferInfo2* pCopyImageToBufferInfo), (commandBuffer, pCopyImageToBufferInfo))
PW_VK_RADV_FN_VOID(vkCmdBlitImage, (VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkImageBlit* pRegions, VkFilter filter), (commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions, filter))
PW_VK_RADV_FN_VOID(vkCmdBlitImage2, (VkCommandBuffer commandBuffer, const VkBlitImageInfo2* pBlitImageInfo), (commandBuffer, pBlitImageInfo))
PW_VK_RADV_FN_VOID(vkCmdResolveImage, (VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkImageResolve* pRegions), (commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions))
PW_VK_RADV_FN_VOID(vkCmdResolveImage2, (VkCommandBuffer commandBuffer, const VkResolveImageInfo2* pResolveImageInfo), (commandBuffer, pResolveImageInfo))
PW_VK_RADV_FN_VOID(vkCmdFillBuffer, (VkCommandBuffer commandBuffer, VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize size, uint32_t data), (commandBuffer, dstBuffer, dstOffset, size, data))
PW_VK_RADV_FN_VOID(vkCmdUpdateBuffer, (VkCommandBuffer commandBuffer, VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize dataSize, const void* pData), (commandBuffer, dstBuffer, dstOffset, dataSize, pData))
PW_VK_RADV_FN_VOID(vkCmdWriteTimestamp, (VkCommandBuffer commandBuffer, VkPipelineStageFlagBits pipelineStage, VkQueryPool queryPool, uint32_t query), (commandBuffer, pipelineStage, queryPool, query))
PW_VK_RADV_FN_VOID(vkCmdWriteTimestamp2, (VkCommandBuffer commandBuffer, VkPipelineStageFlags2 stage, VkQueryPool queryPool, uint32_t query), (commandBuffer, stage, queryPool, query))
PW_VK_RADV_FN_VOID(vkCmdResetQueryPool, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t firstQuery, uint32_t queryCount), (commandBuffer, queryPool, firstQuery, queryCount))
PW_VK_RADV_FN_VOID(vkCmdBeginQuery, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t query, VkQueryControlFlags flags), (commandBuffer, queryPool, query, flags))
PW_VK_RADV_FN_VOID(vkCmdEndQuery, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t query), (commandBuffer, queryPool, query))
PW_VK_RADV_FN_VOID(vkCmdBeginQueryIndexedEXT, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t query, VkQueryControlFlags flags, uint32_t index), (commandBuffer, queryPool, query, flags, index))
PW_VK_RADV_FN_VOID(vkCmdEndQueryIndexedEXT, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t query, uint32_t index), (commandBuffer, queryPool, query, index))
PW_VK_RADV_FN_VOID(vkCmdCopyQueryPoolResults, (VkCommandBuffer commandBuffer, VkQueryPool queryPool, uint32_t firstQuery, uint32_t queryCount, VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize stride, VkQueryResultFlags flags), (commandBuffer, queryPool, firstQuery, queryCount, dstBuffer, dstOffset, stride, flags))
PW_VK_RADV_FN_VOID(vkCmdExecuteCommands, (VkCommandBuffer commandBuffer, uint32_t commandBufferCount, const VkCommandBuffer* pCommandBuffers), (commandBuffer, commandBufferCount, pCommandBuffers))
PW_VK_RADV_FN(vkBeginCommandBuffer, VkResult, (VkCommandBuffer commandBuffer, const VkCommandBufferBeginInfo* pBeginInfo), (commandBuffer, pBeginInfo))
PW_VK_RADV_FN(vkEndCommandBuffer, VkResult, (VkCommandBuffer commandBuffer), (commandBuffer))
PW_VK_RADV_FN(vkResetCommandBuffer, VkResult, (VkCommandBuffer commandBuffer, VkCommandBufferResetFlags flags), (commandBuffer, flags))
PW_VK_RADV_FN(vkResetCommandPool, VkResult, (VkDevice device, VkCommandPool commandPool, VkCommandPoolResetFlags flags), (device, commandPool, flags))
PW_VK_RADV_FN(vkAllocateCommandBuffers, VkResult, (VkDevice device, const VkCommandBufferAllocateInfo* pAllocateInfo, VkCommandBuffer* pCommandBuffers), (device, pAllocateInfo, pCommandBuffers))
PW_VK_RADV_FN_VOID(vkFreeCommandBuffers, (VkDevice device, VkCommandPool commandPool, uint32_t commandBufferCount, const VkCommandBuffer* pCommandBuffers), (device, commandPool, commandBufferCount, pCommandBuffers))
PW_VK_RADV_FN(vkCreateCommandPool, VkResult, (VkDevice device, const VkCommandPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkCommandPool* pCommandPool), (device, pCreateInfo, pAllocator, pCommandPool))
PW_VK_RADV_FN_VOID(vkDestroyCommandPool, (VkDevice device, VkCommandPool commandPool, const VkAllocationCallbacks* pAllocator), (device, commandPool, pAllocator))
PW_VK_RADV_FN_HAND(vkAllocateDescriptorSets, VkResult, (VkDevice device, const VkDescriptorSetAllocateInfo* pAllocateInfo, VkDescriptorSet* pDescriptorSets), (device, pAllocateInfo, pDescriptorSets))
PW_VK_RADV_FN(vkFreeDescriptorSets, VkResult, (VkDevice device, VkDescriptorPool descriptorPool, uint32_t descriptorSetCount, const VkDescriptorSet* pDescriptorSets), (device, descriptorPool, descriptorSetCount, pDescriptorSets))
PW_VK_RADV_FN(vkResetDescriptorPool, VkResult, (VkDevice device, VkDescriptorPool descriptorPool, VkDescriptorPoolResetFlags flags), (device, descriptorPool, flags))
PW_VK_RADV_FN(vkCreateDescriptorPool, VkResult, (VkDevice device, const VkDescriptorPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorPool* pDescriptorPool), (device, pCreateInfo, pAllocator, pDescriptorPool))
PW_VK_RADV_FN_VOID(vkDestroyDescriptorPool, (VkDevice device, VkDescriptorPool descriptorPool, const VkAllocationCallbacks* pAllocator), (device, descriptorPool, pAllocator))
PW_VK_RADV_FN_VOID(vkUpdateDescriptorSets, (VkDevice device, uint32_t descriptorWriteCount, const VkWriteDescriptorSet* pDescriptorWrites, uint32_t descriptorCopyCount, const VkCopyDescriptorSet* pDescriptorCopies), (device, descriptorWriteCount, pDescriptorWrites, descriptorCopyCount, pDescriptorCopies))
PW_VK_RADV_FN_VOID(vkUpdateDescriptorSetWithTemplate, (VkDevice device, VkDescriptorSet descriptorSet, VkDescriptorUpdateTemplate descriptorUpdateTemplate, const void* pData), (device, descriptorSet, descriptorUpdateTemplate, pData))
PW_VK_RADV_FN(vkCreateDescriptorUpdateTemplate, VkResult, (VkDevice device, const VkDescriptorUpdateTemplateCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorUpdateTemplate* pDescriptorUpdateTemplate), (device, pCreateInfo, pAllocator, pDescriptorUpdateTemplate))
PW_VK_RADV_FN(vkCreateDescriptorSetLayout, VkResult, (VkDevice device, const VkDescriptorSetLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorSetLayout* pSetLayout), (device, pCreateInfo, pAllocator, pSetLayout))
PW_VK_RADV_FN_VOID(vkDestroyDescriptorSetLayout, (VkDevice device, VkDescriptorSetLayout descriptorSetLayout, const VkAllocationCallbacks* pAllocator), (device, descriptorSetLayout, pAllocator))
PW_VK_RADV_FN(vkCreatePipelineLayout, VkResult, (VkDevice device, const VkPipelineLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkPipelineLayout* pPipelineLayout), (device, pCreateInfo, pAllocator, pPipelineLayout))
PW_VK_RADV_FN_VOID(vkDestroyPipelineLayout, (VkDevice device, VkPipelineLayout pipelineLayout, const VkAllocationCallbacks* pAllocator), (device, pipelineLayout, pAllocator))
PW_VK_RADV_FN_HAND(vkCreateGraphicsPipelines, VkResult, (VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkGraphicsPipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines), (device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines))
PW_VK_RADV_FN_HAND(vkCreateComputePipelines, VkResult, (VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkComputePipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines), (device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines))
PW_VK_RADV_FN_VOID(vkDestroyPipeline, (VkDevice device, VkPipeline pipeline, const VkAllocationCallbacks* pAllocator), (device, pipeline, pAllocator))
PW_VK_RADV_FN_HAND(vkCreateShaderModule, VkResult, (VkDevice device, const VkShaderModuleCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkShaderModule* pShaderModule), (device, pCreateInfo, pAllocator, pShaderModule))
PW_VK_RADV_FN_VOID(vkDestroyShaderModule, (VkDevice device, VkShaderModule shaderModule, const VkAllocationCallbacks* pAllocator), (device, shaderModule, pAllocator))
PW_VK_RADV_FN_VOID(vkGetShaderModuleIdentifierEXT, (VkDevice device, VkShaderModule shaderModule, VkShaderModuleIdentifierEXT* pIdentifier), (device, shaderModule, pIdentifier))
PW_VK_RADV_FN_VOID(vkGetShaderModuleCreateInfoIdentifierEXT, (VkDevice device, const VkShaderModuleCreateInfo* pCreateInfo, VkShaderModuleIdentifierEXT* pIdentifier), (device, pCreateInfo, pIdentifier))
PW_VK_RADV_FN(vkCreatePipelineCache, VkResult, (VkDevice device, const VkPipelineCacheCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkPipelineCache* pPipelineCache), (device, pCreateInfo, pAllocator, pPipelineCache))
PW_VK_RADV_FN(vkGetPipelineCacheData, VkResult, (VkDevice device, VkPipelineCache pipelineCache, size_t* pDataSize, void* pData), (device, pipelineCache, pDataSize, pData))
PW_VK_RADV_FN(vkCreateSampler, VkResult, (VkDevice device, const VkSamplerCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSampler* pSampler), (device, pCreateInfo, pAllocator, pSampler))
PW_VK_RADV_FN_VOID(vkDestroySampler, (VkDevice device, VkSampler sampler, const VkAllocationCallbacks* pAllocator), (device, sampler, pAllocator))
PW_VK_RADV_FN_HAND(vkCreateBuffer, VkResult, (VkDevice device, const VkBufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkBuffer* pBuffer), (device, pCreateInfo, pAllocator, pBuffer))
PW_VK_RADV_FN_VOID(vkDestroyBuffer, (VkDevice device, VkBuffer buffer, const VkAllocationCallbacks* pAllocator), (device, buffer, pAllocator))
PW_VK_RADV_FN(vkCreateBufferView, VkResult, (VkDevice device, const VkBufferViewCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkBufferView* pView), (device, pCreateInfo, pAllocator, pView))
PW_VK_RADV_FN_VOID(vkDestroyBufferView, (VkDevice device, VkBufferView bufferView, const VkAllocationCallbacks* pAllocator), (device, bufferView, pAllocator))
PW_VK_RADV_FN_HAND(vkCreateImage, VkResult, (VkDevice device, const VkImageCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImage* pImage), (device, pCreateInfo, pAllocator, pImage))
PW_VK_RADV_FN_VOID(vkDestroyImage, (VkDevice device, VkImage image, const VkAllocationCallbacks* pAllocator), (device, image, pAllocator))
PW_VK_RADV_FN(vkCreateImageView, VkResult, (VkDevice device, const VkImageViewCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImageView* pView), (device, pCreateInfo, pAllocator, pView))
PW_VK_RADV_FN_VOID(vkDestroyImageView, (VkDevice device, VkImageView imageView, const VkAllocationCallbacks* pAllocator), (device, imageView, pAllocator))
PW_VK_RADV_FN_VOID(vkGetBufferMemoryRequirements, (VkDevice device, VkBuffer buffer, VkMemoryRequirements* pMemoryRequirements), (device, buffer, pMemoryRequirements))
PW_VK_RADV_FN_VOID(vkGetBufferMemoryRequirements2, (VkDevice device, const VkBufferMemoryRequirementsInfo2* pInfo, VkMemoryRequirements2* pMemoryRequirements), (device, pInfo, pMemoryRequirements))
PW_VK_RADV_FN_VOID(vkGetImageMemoryRequirements, (VkDevice device, VkImage image, VkMemoryRequirements* pMemoryRequirements), (device, image, pMemoryRequirements))
PW_VK_RADV_FN_VOID(vkGetImageMemoryRequirements2, (VkDevice device, const VkImageMemoryRequirementsInfo2* pInfo, VkMemoryRequirements2* pMemoryRequirements), (device, pInfo, pMemoryRequirements))
PW_VK_RADV_FN_VOID(vkGetDeviceBufferMemoryRequirements, (VkDevice device, const VkDeviceBufferMemoryRequirements* pInfo, VkMemoryRequirements2* pMemoryRequirements), (device, pInfo, pMemoryRequirements))
PW_VK_RADV_FN_VOID(vkGetDeviceImageMemoryRequirements, (VkDevice device, const VkDeviceImageMemoryRequirements* pInfo, VkMemoryRequirements2* pMemoryRequirements), (device, pInfo, pMemoryRequirements))
PW_VK_RADV_FN_VOID(vkGetImageSubresourceLayout, (VkDevice device, VkImage image, const VkImageSubresource* pSubresource, VkSubresourceLayout* pLayout), (device, image, pSubresource, pLayout))
PW_VK_RADV_FN_VOID(vkGetDeviceImageSubresourceLayoutKHR, (VkDevice device, const VkDeviceImageSubresourceInfo* pInfo, VkSubresourceLayout2* pLayout), (device, pInfo, pLayout))
PW_VK_RADV_FN_HAND(vkAllocateMemory, VkResult, (VkDevice device, const VkMemoryAllocateInfo* pAllocateInfo, const VkAllocationCallbacks* pAllocator, VkDeviceMemory* pMemory), (device, pAllocateInfo, pAllocator, pMemory))
PW_VK_RADV_FN_VOID(vkFreeMemory, (VkDevice device, VkDeviceMemory memory, const VkAllocationCallbacks* pAllocator), (device, memory, pAllocator))
PW_VK_RADV_FN_HAND(vkMapMemory, VkResult, (VkDevice device, VkDeviceMemory memory, VkDeviceSize offset, VkDeviceSize size, VkMemoryMapFlags flags, void** ppData), (device, memory, offset, size, flags, ppData))
PW_VK_RADV_FN_VOID(vkUnmapMemory, (VkDevice device, VkDeviceMemory memory), (device, memory))
PW_VK_RADV_FN(vkFlushMappedMemoryRanges, VkResult, (VkDevice device, uint32_t memoryRangeCount, const VkMappedMemoryRange* pMemoryRanges), (device, memoryRangeCount, pMemoryRanges))
PW_VK_RADV_FN(vkInvalidateMappedMemoryRanges, VkResult, (VkDevice device, uint32_t memoryRangeCount, const VkMappedMemoryRange* pMemoryRanges), (device, memoryRangeCount, pMemoryRanges))
PW_VK_RADV_FN(vkBindBufferMemory, VkResult, (VkDevice device, VkBuffer buffer, VkDeviceMemory memory, VkDeviceSize memoryOffset), (device, buffer, memory, memoryOffset))
PW_VK_RADV_FN(vkBindBufferMemory2, VkResult, (VkDevice device, uint32_t bindInfoCount, const VkBindBufferMemoryInfo* pBindInfos), (device, bindInfoCount, pBindInfos))
PW_VK_RADV_FN(vkBindImageMemory, VkResult, (VkDevice device, VkImage image, VkDeviceMemory memory, VkDeviceSize memoryOffset), (device, image, memory, memoryOffset))
PW_VK_RADV_FN(vkBindImageMemory2, VkResult, (VkDevice device, uint32_t bindInfoCount, const VkBindImageMemoryInfo* pBindInfos), (device, bindInfoCount, pBindInfos))
PW_VK_RADV_FN(vkGetBufferDeviceAddress, VkDeviceAddress, (VkDevice device, const VkBufferDeviceAddressInfo* pInfo), (device, pInfo))
PW_VK_RADV_FN(vkCreateFence, VkResult, (VkDevice device, const VkFenceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFence* pFence), (device, pCreateInfo, pAllocator, pFence))
PW_VK_RADV_FN_VOID(vkDestroyFence, (VkDevice device, VkFence fence, const VkAllocationCallbacks* pAllocator), (device, fence, pAllocator))
PW_VK_RADV_FN(vkResetFences, VkResult, (VkDevice device, uint32_t fenceCount, const VkFence* pFences), (device, fenceCount, pFences))
PW_VK_RADV_FN_HAND(vkWaitForFences, VkResult, (VkDevice device, uint32_t fenceCount, const VkFence* pFences, VkBool32 waitAll, uint64_t timeout), (device, fenceCount, pFences, waitAll, timeout))
PW_VK_RADV_FN(vkGetFenceStatus, VkResult, (VkDevice device, VkFence fence), (device, fence))
PW_VK_RADV_FN(vkCreateSemaphore, VkResult, (VkDevice device, const VkSemaphoreCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSemaphore* pSemaphore), (device, pCreateInfo, pAllocator, pSemaphore))
PW_VK_RADV_FN_VOID(vkDestroySemaphore, (VkDevice device, VkSemaphore semaphore, const VkAllocationCallbacks* pAllocator), (device, semaphore, pAllocator))
PW_VK_RADV_FN_HAND(vkWaitSemaphores, VkResult, (VkDevice device, const VkSemaphoreWaitInfo* pWaitInfo, uint64_t timeout), (device, pWaitInfo, timeout))
PW_VK_RADV_FN(vkSignalSemaphore, VkResult, (VkDevice device, const VkSemaphoreSignalInfo* pSignalInfo), (device, pSignalInfo))
PW_VK_RADV_FN(vkGetSemaphoreCounterValue, VkResult, (VkDevice device, VkSemaphore semaphore, uint64_t* pValue), (device, semaphore, pValue))
PW_VK_RADV_FN(vkCreateEvent, VkResult, (VkDevice device, const VkEventCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkEvent* pEvent), (device, pCreateInfo, pAllocator, pEvent))
PW_VK_RADV_FN(vkResetEvent, VkResult, (VkDevice device, VkEvent event), (device, event))
PW_VK_RADV_FN(vkCreateQueryPool, VkResult, (VkDevice device, const VkQueryPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkQueryPool* pQueryPool), (device, pCreateInfo, pAllocator, pQueryPool))
PW_VK_RADV_FN_VOID(vkDestroyQueryPool, (VkDevice device, VkQueryPool queryPool, const VkAllocationCallbacks* pAllocator), (device, queryPool, pAllocator))
PW_VK_RADV_FN(vkGetQueryPoolResults, VkResult, (VkDevice device, VkQueryPool queryPool, uint32_t firstQuery, uint32_t queryCount, size_t dataSize, void* pData, VkDeviceSize stride, VkQueryResultFlags flags), (device, queryPool, firstQuery, queryCount, dataSize, pData, stride, flags))
PW_VK_RADV_FN_VOID(vkResetQueryPool, (VkDevice device, VkQueryPool queryPool, uint32_t firstQuery, uint32_t queryCount), (device, queryPool, firstQuery, queryCount))
PW_VK_RADV_FN_HAND(vkQueueSubmit, VkResult, (VkQueue queue, uint32_t submitCount, const VkSubmitInfo* pSubmits, VkFence fence), (queue, submitCount, pSubmits, fence))
PW_VK_RADV_FN_HAND(vkQueueSubmit2, VkResult, (VkQueue queue, uint32_t submitCount, const VkSubmitInfo2* pSubmits, VkFence fence), (queue, submitCount, pSubmits, fence))
PW_VK_RADV_FN(vkQueueWaitIdle, VkResult, (VkQueue queue), (queue))
PW_VK_RADV_FN(vkDeviceWaitIdle, VkResult, (VkDevice device), (device))
PW_VK_RADV_FN_HAND(vkQueuePresentKHR, VkResult, (VkQueue queue, const VkPresentInfoKHR* pPresentInfo), (queue, pPresentInfo))
PW_VK_RADV_FN_HAND(vkAcquireNextImageKHR, VkResult, (VkDevice device, VkSwapchainKHR swapchain, uint64_t timeout, VkSemaphore semaphore, VkFence fence, uint32_t* pImageIndex), (device, swapchain, timeout, semaphore, fence, pImageIndex))
PW_VK_RADV_FN(vkCreateSwapchainKHR, VkResult, (VkDevice device, const VkSwapchainCreateInfoKHR* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSwapchainKHR* pSwapchain), (device, pCreateInfo, pAllocator, pSwapchain))
PW_VK_RADV_FN_VOID(vkDestroySwapchainKHR, (VkDevice device, VkSwapchainKHR swapchain, const VkAllocationCallbacks* pAllocator), (device, swapchain, pAllocator))
PW_VK_RADV_FN(vkGetSwapchainImagesKHR, VkResult, (VkDevice device, VkSwapchainKHR swapchain, uint32_t* pSwapchainImageCount, VkImage* pSwapchainImages), (device, swapchain, pSwapchainImageCount, pSwapchainImages))
PW_VK_RADV_FN_HAND(vkWaitForPresentKHR, VkResult, (VkDevice device, VkSwapchainKHR swapchain, uint64_t presentId, uint64_t timeout), (device, swapchain, presentId, timeout))
PW_VK_RADV_FN(vkCreateRenderPass, VkResult, (VkDevice device, const VkRenderPassCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkRenderPass* pRenderPass), (device, pCreateInfo, pAllocator, pRenderPass))
PW_VK_RADV_FN(vkCreateRenderPass2, VkResult, (VkDevice device, const VkRenderPassCreateInfo2* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkRenderPass* pRenderPass), (device, pCreateInfo, pAllocator, pRenderPass))
PW_VK_RADV_FN(vkCreateFramebuffer, VkResult, (VkDevice device, const VkFramebufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFramebuffer* pFramebuffer), (device, pCreateInfo, pAllocator, pFramebuffer))
PW_VK_RADV_FN_VOID(vkDestroyFramebuffer, (VkDevice device, VkFramebuffer framebuffer, const VkAllocationCallbacks* pAllocator), (device, framebuffer, pAllocator))
PW_VK_RADV_FN_VOID(vkGetDeviceQueue, (VkDevice device, uint32_t queueFamilyIndex, uint32_t queueIndex, VkQueue* pQueue), (device, queueFamilyIndex, queueIndex, pQueue))
