#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""Generate the PRXDESC1 export descriptor for one of Wine's Unix modules.

On firmware 12.02 sceKernelDlsym does not resolve an application PRX's
exports, so every Wine PRX links one generated unit that carries:

- ``pw_prx_exports``: the relocated {name, address} table that
  wine/ps5/pw_wine_prx.c finds by scanning the module's segments;
- ``module_start``: runs the module's constructors (``.init_array``) once.
  The converter makes it the module's entry, which the firmware loader
  calls, and wine/ps5/pw_wine_dl.c calls it again through the table; the
  first constructor marks the module started, so whichever of the firmware,
  a C runtime or module_start runs the array first, it runs only once;
- ``module_stop``: a no-op; Wine's Unix modules are never unloaded.

Use --optional-from ELF --optional-export NAME [--nm TOOL] to publish an
additional name only when the input ELF defines it in its dynamic exports.
Missing, hidden and undefined names are omitted; inspection failures are errors.

Usage: gen_prx_descriptor.py OUTPUT.c NAME...
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

RESERVED = {"module_start", "module_stop", "pw_prx_exports"}
IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")


def render(names):
    if not names:
        raise ValueError("no exports")
    for name in names:
        if not IDENTIFIER.match(name):
            raise ValueError(f"not a C identifier: {name}")
        if name in RESERVED:
            raise ValueError(f"reserved name: {name}")
    if len(set(names)) != len(names):
        raise ValueError("duplicate export")
    count = len(names) + 1
    # Functions and variables alike are declared as char arrays: only their
    # addresses are taken, so the unit needs none of the modules' headers.
    externs = "".join(f"extern char {name}[];\n" for name in names)
    entries = "".join(f'        {{ "{name}", {name} }},\n' for name in names)
    return f"""/* Generated by tools/gen_prx_descriptor.py; do not edit. */
#include "pw_wine_prx.h"
#include <stddef.h>

{externs}extern void (*__init_array_start[])(void) __attribute__((visibility("hidden")));
extern void (*__init_array_end[])(void) __attribute__((visibility("hidden")));

/* volatile: a compiler may otherwise evaluate the marker below at build
 * time and start the module already marked, never running its array. */
static volatile int started;

/* First in .init_array: whoever runs the array marks the module started. */
__attribute__((constructor(101))) static void pw_prx_mark_started(void) {{ started = 1; }}

int module_start(size_t argc, const void *argv)
{{
    (void)argc; (void)argv;
    if (!started)
    {{
        started = 1;
        for (void (**init)(void) = __init_array_start; init < __init_array_end; init++) (*init)();
    }}
    return 0;
}}

int module_stop(size_t argc, const void *argv)
{{
    (void)argc; (void)argv;
    return 0;
}}

struct pw_prx_exports_table {{
    uint64_t magic;
    uint32_t version, count;
    PwPrxExport exports[{count}];
}};
_Static_assert(offsetof(struct pw_prx_exports_table, exports) == offsetof(PwPrxDescriptor, exports),
               "PRXDESC1 layout");

__attribute__((used, aligned(PW_PRX_ALIGN)))
const struct pw_prx_exports_table pw_prx_exports = {{
    PW_PRX_MAGIC, PW_PRX_VERSION, {count}, {{
{entries}        {{ "module_start", (const void *)module_start }},
    }}
}};
"""


def main(argv):
    if len(argv) < 3:
        print(__doc__.strip().splitlines()[-1], file=sys.stderr)
        return 2
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output")
    parser.add_argument("names", nargs="+")
    parser.add_argument("--optional-from", type=Path,
                        help="ELF whose defined dynamic exports select optional names")
    parser.add_argument("--optional-export", action="append", default=[])
    parser.add_argument("--nm", default="nm", help="nm executable for the input ELF")
    args = parser.parse_args(argv[1:])
    try:
        # Validate even optional names that are absent from an older module.
        render(args.names + args.optional_export)
        names = args.names[:]
        if args.optional_export:
            if args.optional_from is None:
                raise ValueError("optional exports require --optional-from")
            try:
                result = subprocess.run([args.nm, "-D", "--defined-only", "--format=posix",
                                         str(args.optional_from)],
                                        check=True, capture_output=True, text=True)
            except (OSError, subprocess.CalledProcessError) as error:
                raise ValueError(f"cannot inspect optional exports: {error}") from error
            defined = {parts[0].split("@", 1)[0] for line in result.stdout.splitlines()
                       if len(parts := line.split()) >= 2 and parts[1].upper() != "U"}
            names += [name for name in args.optional_export if name in defined]
        text = render(names)
    except ValueError as error:
        print(f"gen_prx_descriptor: {error}", file=sys.stderr)
        return 1
    Path(args.output).write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
