#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""Generate fail-closed D3D9 method inventories from the pinned Wine header."""
import argparse
import hashlib
from pathlib import Path
import re

HEADER_SHA256 = 'fb49b3c44acec5e100a5c0ff1622f7d0207842d87fc513b49047a818e8c351b2'
COUNTS = {
    'IDirect3D9': 17, 'IDirect3DVolume9': 11, 'IDirect3DSwapChain9': 10,
    'IDirect3DResource9': 11, 'IDirect3DSurface9': 17,
    'IDirect3DVertexBuffer9': 14, 'IDirect3DIndexBuffer9': 14,
    'IDirect3DBaseTexture9': 17, 'IDirect3DCubeTexture9': 22,
    'IDirect3DTexture9': 22, 'IDirect3DVolumeTexture9': 22,
    'IDirect3DVertexDeclaration9': 5, 'IDirect3DVertexShader9': 5,
    'IDirect3DPixelShader9': 5, 'IDirect3DStateBlock9': 6,
    'IDirect3DQuery9': 8, 'IDirect3DDevice9': 119,
}
INTERFACE = re.compile(r'DECLARE_INTERFACE_IID_\((\w+),[^\n]+\)\s*\{(.*?)\n\};', re.S)
METHOD = re.compile(r'STDMETHOD(?:_\(([^,]+),\s*(\w+)\)|\((\w+)\))\((.*?)\)\s*PURE;', re.S)

def parse(source):
    """No inferred inheritance: Wine explicitly repeats inherited vtable slots."""
    source = re.sub(r'/\*.*?\*/', '', source, flags=re.S)
    result = {}
    for interface, body in INTERFACE.findall(source):
        if interface not in COUNTS:
            continue
        if interface in result:
            raise ValueError('duplicate interface: ' + interface)
        methods = []
        for match in METHOD.finditer(body):
            returned, underscored, normal, args = match.groups()
            name = underscored or normal
            args = ' '.join(args.split())
            if args == 'THIS':
                args = ''
            elif args.startswith('THIS_ '):
                args = args[6:]
            else:
                raise ValueError('missing explicit this: ' + name)
            methods.append((name, (returned or 'HRESULT').strip(), args))
        if METHOD.sub('', body).strip():
            raise ValueError('unparsed interface declaration: ' + interface)
        if len({m[0] for m in methods}) != len(methods):
            raise ValueError('duplicate method: ' + interface)
        result[interface] = methods
    return result

def policy(interface, slot):
    if slot < 3:
        return 'PW_D3D9_POLICY_LOCAL_IDENTITY'
    if interface == 'IDirect3D9' and 4 <= slot <= 14:
        return 'PW_D3D9_POLICY_SYNC_FACTORY'
    return 'PW_D3D9_POLICY_UNSUPPORTED'

def render(interfaces):
    if {k: len(v) for k, v in interfaces.items()} != COUNTS:
        raise ValueError('interface inventory changed')
    for name, methods in interfaces.items():
        if [m[0] for m in methods[:3]] != ['QueryInterface', 'AddRef', 'Release']:
            raise ValueError('IUnknown layout changed: ' + name)
    lines = [
        '/* SPDX-License-Identifier: LGPL-2.1-or-later */',
        '/* Generated by tools/generate_d3d9_inventory.py; do not edit. */',
        '#ifndef PW_D3D9_INVENTORY_H', '#define PW_D3D9_INVENTORY_H',
        f'#define PW_D3D9_HEADER_SHA256 "{HEADER_SHA256}"',
        '/* Policies are obligations, not an automatic runtime enable list. */',
        'enum pw_d3d9_method_policy {',
        '    PW_D3D9_POLICY_UNSUPPORTED, PW_D3D9_POLICY_LOCAL_IDENTITY,',
        '    PW_D3D9_POLICY_SYNC_FACTORY', '};',
        '/* X(interface, slot, name, return_type, (explicit parameters), policy).',
        ' * Explicit parameters include the typed self pointer. Native signatures',
        ' * are for compile checks/local proxies; never copy them onto the wire. */',
    ]
    for interface, methods in interfaces.items():
        lines.append(f'#define PW_D3D9_METHODS_{interface}(X) \\')
        for slot, (name, returned, args) in enumerate(methods):
            parameters = interface + ' *self' + (', ' + args if args else '')
            suffix = ' \\' if slot + 1 < len(methods) else ''
            lines.append(f'    X({interface}, {slot}, {name}, {returned}, ({parameters}), {policy(interface, slot)}){suffix}')
        lines.append('')
    lines.append('#define PW_D3D9_INTERFACES(X) \\')
    for index, (interface, count) in enumerate(COUNTS.items()):
        suffix = ' \\' if index + 1 < len(COUNTS) else ''
        lines.append(f'    X({interface}, {count}){suffix}')
    lines.append('#define PW_D3D9_ALL_METHODS(X) \\')
    for index, interface in enumerate(COUNTS):
        suffix = ' \\' if index + 1 < len(COUNTS) else ''
        lines.append(f'    PW_D3D9_METHODS_{interface}(X){suffix}')
    lines.extend(['#endif', ''])
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--header', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    raw = args.header.read_bytes()
    if hashlib.sha256(raw).hexdigest() != HEADER_SHA256:
        parser.error('header differs from the pinned Wine d3d9.h')
    text = render(parse(raw.decode()))
    if args.check:
        if args.output.read_text() != text:
            parser.error('generated inventory differs')
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text)

if __name__ == '__main__':
    main()
